### ISSUE TITLE
对AFBrushBoard.swift, Line 105.中let len = Int(sqrt(pow(x1, 2) + pow(x2,2))*10)的疑问

### ISSUE THREAD

**Issue by jeffssss** [AfryMask/AFBrushBoard#1]
你好，AFBrushBoard的Demo让我受益良多，然而能力有限，接触的东西不多，有一些地方我没有弄懂，希望能得到解答：

在AFBrushBoard.swift, Line 105.

``` swift
let len = Int(sqrt(pow(x1, 2) + pow(x2,2))*10)
```
1. 在网上略微看了三次贝塞尔曲线长度计算的一些资料，计算长度是需要积分的。此处的估算是直接_10处理。想请问一下此处为何是_10处理。
2. 每次changeImage()打印len的值，发现在屏幕滑动很小一截，len都会上百。（虽然绘制过程中会省略多余的点）len的值的粒度定这么细是有特殊的意义么？

谢谢。

**Comment by AfryMask** [comment]
你好。
- 因为如果系数是1的话，通过贝塞尔曲线工具获得到的点在“接近起始或末尾点”比“曲线的中间点”密集度小。并且作图方法是“无数个短线段叠加而成”。所以，会造成每条线的浓度不均的情况（在相同线宽的情况下）。
  此外，Line 156 处的 “1” 起到了配合作用。

``` swift
 if delta < 1 {continue} 
```
- 这两个数的具体值问题：是根据“手机性能”和“绘图效果”同时考虑的情况下的折中方案。
- 现在做的这个demo其实仅仅用到了二次贝塞尔曲线（虽然把贝塞尔函数封装了一下）。在后续的版本中会有算法的变动，会用到多次贝塞尔曲线。
