### ISSUE TITLE
希望能通过CocoaPods引入到工程

### ISSUE THREAD

**Issue by crespoxiao** [AfryMask/AFBrushBoard#3]
可以考虑一下，谢谢

**Comment by AfryMask** [comment]
😂抱歉，因为现在的逻辑结构还有待改进，并且暂未设计接口。所以暂时不打算放到pod上边，将来TodoList完成之后再做吧😐

**Comment by crespoxiao** [comment]
打算出个oc版本吗？很多人都在等swift3.0稳定下来后再用。

**Comment by AfryMask** [comment]
😂加我qq详聊吧1185878525

**Comment by AfryMask** [comment]
README中已添加OC版本链接
